name: malinau_absensi
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  cupertino_icons: ^1.0.8
  dropdown_button2: ^2.3.9
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  provider: ^6.1.2
  camera_camera: ^3.0.0
  permission_handler: ^11.3.1
  shared_preferences: ^2.3.2

dev_dependencies:
  change_app_package_name: ^1.3.0
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/imgs/
    - assets/icons/
